# version: '2'
services:
  web:
    build: .
    stdin_open: true
    tty: true
    platform: linux/arm64
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - .:/mnt/prescrypto-odoo
      - ./addons:/mnt/extra-addons
      - ./prescrypto:/mnt/custom-addons
      - ./output:/var/lib/odoo
      - ./OpenUpgrade:/mnt/OpenUpgrade
    env_file:
      - db_variables

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    # environment:
    #   - POSTGRES_PASSWORD=odoo
    #   - POSTGRES_USER=odoo
    #   - POSTGRES_DB=postgres
    #   - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - db_variables
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/pgadmin/config
      - ./backup:/var/lib/pgadmin/backup
    env_file:
      - db_variables

  # redis:
  #   image: redis:6.2-alpine
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redisdata:/data

volumes:
  pgdata: {}
  pgadmin: {}
  redisdata: {}
